title: "Hudson Morrill – Morrill-Hudson-Portfolio"
description: "AP Networking projects: Getting Started, Silent Signals, Metal to Magic, Component Song"
baseurl: "/Morrill-Hudson-Portfolio"
url: "https://huddy67.github.io"
theme: jekyll-theme-cayman
