title: "Hudson Morrill – Morrill-Hudson-Portfolio"
description: "AP Networking projects: Getting Started, Silent Signals, Metal to Magic, Component Song"
url: "https://<huddy67>.github.io"
baseurl: "/Morrill-Hudson-Portfolio" 
theme: jekyll-theme-cayman
